apiVersion: apps/v1
kind: Deployment
metadata:
  name: trojan
  namespace: trojan
  labels:
    environment: production
    app: trojan
spec:
  selector:
    matchLabels:
      app: trojan
  template:
    metadata:
      labels:
        app: trojan
    spec:
      initContainers:
      - name: wait-for-mariadb
        image: busybox
        command: ['sh', '-c', 'until nc mariadb-service 3306 < /dev/null; do sleep 2; done']
      containers:
      - name: trojan
        image: trojangfw/trojan:1.15.1
        ports:
        - containerPort: 443
        volumeMounts:
        - name: server-config
          mountPath: /config
        - name: tls-cert
          mountPath: /config/tls
      volumes:
      - name: server-config
        configMap:
          name: trojan-server-config
          items:
          - key: server-config
            path: config.json
      - name: tls-cert
        secret:
          secretName: trojan-tls-cert
          items:
          - key: tls.crt
            path: certificate.crt
            mode: 400
          - key: tls.key
            path: private.key
            mode: 400
